- hosts: aws
  become: true

  tasks:
    - name: List contents of 2 directories
      shell: ls "{{ item }}"
      loop:
       - "/etc"
       - "/var"
    
    - name: Cat /etc/redhat-version
      shell: cat /etc/redhat-version
      when:
        - ansible_facts['distribution'] == "CentOS"
        - ansible_facts['distribution_major_version'] == "8"

    - name: Stat folder
      stat:
        path: "{{ folder }}"